Task/drawer
fahjan/gtc_customer pull request #6
Opened 2022-09-09 13:53 UTC by azizalshrafi

Add drawer to project

2022-09-09 15:46 UTC, AbdalazizAbdallah requested changes
in the beginning Thank Abdalaziz for this

1- back icon you can use Icon class and select ios back, don't export anything you can do it
also a number of notifications

solve the conflict in code by pull statement to main branch the locally and again push here 
put your drawer in UI folder inside the widgets folder and use home page to test , after complete UI well separate folder according clean architecture , your work is very good but not at this time

ignore pubspec.lock by put *.lock in .gitignore file in any line

2022-09-09 15:46 UTC, AbdalazizAbdallah commented on lib/core/constants/sizes_app.dart
> +  static final double h20 = 20.2.h;
remove point number

2022-09-09 15:46 UTC, AbdalazizAbdallah commented on lib/core/constants/sizes_app.dart
> +  static final double w54 = 54.w;
use r instead of w

2022-09-09 15:46 UTC, AbdalazizAbdallah commented on lib/core/routes/routes_app.dart
> +    fullscreenDialog: true,
useless here, we won't show a dialog

2022-09-09 15:46 UTC, AbdalazizAbdallah commented on lib/home_page.dart
> +final GlobalKey<ScaffoldState> _key = GlobalKey();
add any Global Keys in controllers not inside page , to show your code WOW ^_^

2022-09-09 15:46 UTC, AbdalazizAbdallah commented on lib/home_page.dart
> +            width: SizesApp.w23,
r instead of w, Is this square? so use same variable

2022-09-09 15:46 UTC, AbdalazizAbdallah commented on lib/presentation/pages/drawer.dart
> +              width: SizesApp.w24,
same pervious review ^_^

2022-09-09 15:46 UTC, AbdalazizAbdallah commented on lib/presentation/pages/drawer.dart
> +        padding: EdgeInsets.only(top: 40),
put 40.r in SizesApp

2022-09-09 15:46 UTC, AbdalazizAbdallah commented on lib/presentation/pages/drawer.dart
> +              Container(
learn about DrawerHeader widgets and maybe use it

2022-09-09 15:46 UTC, AbdalazizAbdallah commented on lib/presentation/pages/drawer.dart
> +            padding: const EdgeInsets.only(left: 30),
30.r in SizesApp

2022-09-09 15:46 UTC, AbdalazizAbdallah commented on lib/presentation/pages/drawer.dart
> +                    text: 'My_Order',
try to make keys small char like my_order

2022-09-09 20:26 UTC, AbdalazizAbdallah commented on lib/presentation/controllers/drawer_controller.dart
> +final GlobalKey<ScaffoldState> drawerkey = GlobalKey();
inside controller and access by controller declared in page ...
but in this case, I agree,

2022-09-09 20:30 UTC, AbdalazizAbdallah commented
**in the beginning Thank Abdalaziz for this**

1- back icon you can use Icon class and select ios back, don't export anything you can do it
also a number of notifications

2- solve the conflict in code by pull statement to the main branch locally and again pushing here
3- put your drawer in the UI folder inside the widgets folder and use the home page to test, after complete UI well separate the folder according to to clean architecture, your work is very good but not at this time**###  till the rest of the members develop without conflict** 

4- ignore pubspec.lock by put *.lock in .gitignore file in any line

2022-09-11 15:14 UTC, fahjan commented on lib/presentation/controllers/drawer_controller.dart
> +final GlobalKey<ScaffoldState> drawerkey = GlobalKey();
move this to controller body

2022-09-11 15:15 UTC, fahjan commented on lib/presentation/pages/drawer.dart
> +                custom_ListTile(
don't use underscore in custom widgets.

2022-09-11 15:16 UTC, fahjan commented on lib/presentation/widget/custom_ListTile.dart
> +class custom_ListTile extends StatelessWidget {
use this please, CustomListTile

2022-09-11 15:16 UTC, fahjan commented on pubspec.lock
> +# Generated by pub
ignore this file please.

2022-09-12 00:08 UTC, mohammedalian reviewed
resolve conflicts

2022-09-15 15:48 UTC, merged