create about us screen
fahjan/gtc_customer pull request #9
Opened 2022-09-12 19:34 UTC by abdkhamis

create about us page
create about us controller
create about us bindings
add in sizeApp & colorsApp & imagesApp

2022-09-12 19:58 UTC, AbdalazizAbdallah commented on lib/core/constants/images_app.dart
>    static const String logoPath = '${_baseSvgPath}whole_logo.svg';
where is the whole logo in the assets file? I added it when we were in class

2022-09-12 19:58 UTC, AbdalazizAbdallah commented on lib/core/constants/images_app.dart
>    static const String logoPath = '${_baseSvgPath}whole_logo.svg';
where is the white whole logo in the assets file? I added it when we were in class

2022-09-12 20:00 UTC, AbdalazizAbdallah commented on lib/core/constants/images_app.dart
> +  static const String daddyEatPath = '${_baseSvgPath}daddyEat.svg';
remove logo and daddyEat, and use whole_logo.svg
because whole logo already contains logo and daddyEat

2022-09-12 20:01 UTC, AbdalazizAbdallah commented on lib/core/constants/sizes_app.dart
> +  static final double px30 = 30.r;
change px30 to r30

2022-09-12 20:01 UTC, AbdalazizAbdallah commented on lib/core/constants/sizes_app.dart
> +  static final double w123 = 123.r;
w123 to 123.r

2022-09-12 20:02 UTC, AbdalazizAbdallah commented on lib/core/constants/sizes_app.dart
> +  static final double h14 = 14.4.r;
remove point numbers just 14.r

2022-09-12 20:02 UTC, AbdalazizAbdallah commented on lib/core/localizations/ar.dart
> +  'Learn_how_we_work': 'تعلم كيف نعمل',
Learn_how_we_work ==> learn_how_we_work

2022-09-12 20:04 UTC, AbdalazizAbdallah commented on lib/ui/controllers/aboutUs_controller.dart
> +class AboutUsController extends GetxController {}
remove this class , your work is very good when make for every page controller but this time don't please

2022-09-12 20:05 UTC, AbdalazizAbdallah commented on lib/core/constants/sizes_app.dart
> +  static final double h45 = 45.r;
h17 => r17

2022-09-12 20:06 UTC, AbdalazizAbdallah commented on lib/ui/pages/aboutUs_page.dart
> +              child: Row(
in AppBar not here

2022-09-12 20:08 UTC, AbdalazizAbdallah commented on lib/ui/pages/aboutUs_page.dart
> +                    style: GoogleFonts.openSans(
move this to the stylesApp file and declare according to Texts Schema I sent in Whatsapp group like this

 /// [headline6] ==> 20.sp openSans font1
  static final TextStyle headline6 = GoogleFonts.openSans(
    fontSize: SizesApp.sp20,
  );

2022-09-12 20:11 UTC, AbdalazizAbdallah commented on lib/ui/pages/aboutUs_page.dart
> +              padding: EdgeInsets.only(
WOW is very good, I prefer using symmetric constractor such as

EdgeInsets.symmetric(horizontal: SizesApp.r48)

2022-09-12 20:12 UTC, AbdalazizAbdallah commented on lib/ui/pages/aboutUs_page.dart
> +                    style: GoogleFonts.openSans(
same above note
move this to the stylesApp file and declare according to Texts Schema I sent in Whatsapp group like this

body2   14

2022-09-12 20:14 UTC, AbdalazizAbdallah commented on lib/ui/pages/aboutUs_page.dart
> +                          style: GoogleFonts.openSans(
when using StylesApp.body2 , you can change any property like color and wight  by 

StylesApp.body2.copyWith(.......)

2022-09-12 20:16 UTC, AbdalazizAbdallah commented on lib/ui/pages/aboutUs_page.dart
> +                  child: Row(
use ListTile may be best than row

2022-09-12 20:19 UTC, AbdalazizAbdallah commented on pubspec.lock
>      version: "1.16.0"
ingore this by put *.lock in gitingore fie after that delete it

2022-09-12 20:47 UTC, AbdalazizAbdallah requested changes
seriously the page is very beautiful, I look at it, but it needs some changes to be is goooood 
look at notes and make your design perfect

additions notes:
try to use even numbers like 10 12 14 don't use odd 13 
think in your design and try optimation by extracting custom widget
define the App bar theme in ThemesApp and try share to rest members 

finally MaShaAllah

2022-09-14 03:20 UTC, fahjan commented on lib/ui/pages/aboutUs_page.dart
> +                  child: Row(
if it works perfectly, we can let it Row

2022-09-14 03:21 UTC, fahjan commented on lib/ui/pages/aboutUs_page.dart
> +                  child: Container(
write a link here please.
@AbdalazizAbdallah

2022-09-14 10:38 UTC, abdkhamis commented on lib/core/constants/images_app.dart
>    static const String logoPath = '${_baseSvgPath}whole_logo.svg';
solve

2022-09-14 10:41 UTC, abdkhamis commented on lib/core/constants/sizes_app.dart
> +  static final double px30 = 30.r;
solve

2022-09-14 10:54 UTC, abdkhamis commented on lib/ui/pages/aboutUs_page.dart
> +              child: Row(
there is no AppBar in design?!

2022-09-14 17:03 UTC, fahjan commented on lib/bindings/aboutUs_binding.dart
> +import 'package:get/get.dart';
don't use capital letters in filenames :
`aboutUs_binding.dart`

2022-09-14 17:05 UTC, fahjan commented on lib/ui/pages/aboutUs_page.dart
> +                  child: Container(
to help your friend

2022-09-18 13:01 UTC, abdkhamis commented on lib/core/constants/images_app.dart
> +  static const String daddyEatPath = '${_baseSvgPath}daddyEat.svg';
my logo different from your logo 
look at design

2022-09-18 13:02 UTC, abdkhamis commented on lib/core/constants/sizes_app.dart
> +  static final double px30 = 30.r;
solve

2022-09-18 13:02 UTC, abdkhamis commented on lib/core/constants/sizes_app.dart
> +  static final double w123 = 123.r;
solve

2022-09-18 13:02 UTC, abdkhamis commented on lib/core/constants/sizes_app.dart
> +  static final double h14 = 14.4.r;
solve

2022-09-18 13:02 UTC, abdkhamis commented on lib/core/localizations/ar.dart
> +  'Learn_how_we_work': 'تعلم كيف نعمل',
solve

2022-09-18 13:02 UTC, abdkhamis commented on lib/core/constants/sizes_app.dart
> +  static final double h45 = 45.r;
solve

2022-09-18 13:03 UTC, abdkhamis commented on lib/ui/pages/aboutUs_page.dart
> +              child: Row(
solve

2022-09-18 13:03 UTC, abdkhamis commented on lib/ui/pages/aboutUs_page.dart
> +                    style: GoogleFonts.openSans(
solve

2022-09-18 13:03 UTC, abdkhamis commented on lib/ui/pages/aboutUs_page.dart
> +              padding: EdgeInsets.only(
solve

2022-09-18 13:03 UTC, abdkhamis commented on lib/ui/pages/aboutUs_page.dart
> +                    style: GoogleFonts.openSans(
solve

2022-09-18 13:03 UTC, abdkhamis commented on lib/ui/pages/aboutUs_page.dart
> +                          style: GoogleFonts.openSans(
solve

2022-09-18 13:03 UTC, abdkhamis commented on pubspec.lock
>      version: "1.16.0"
solve

2022-09-18 13:07 UTC, abdkhamis commented on lib/ui/pages/aboutUs_page.dart
> +                  child: Container(
solve

2022-09-18 17:12 UTC, AbdalazizAbdallah approved these changes
good work but maybe in the future you need to refactor the code when merging with others to make our code consistent such use AppBar as global

2022-09-18 17:12 UTC, merged